// Code generated by "stringer -type=NodeState"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Empty-0]
	_ = x[Cone-1]
	_ = x[Cube-2]
	_ = x[TwoCones-3]
	_ = x[TwoCubes-4]
	_ = x[ConeThenCube-5]
	_ = x[CubeThenCone-6]
	_ = x[NodeStateCount-7]
	_ = x[BlueCargo-8]
	_ = x[Gear-9]
	_ = x[RedCargo-10]
	_ = x[WhiteCrate-11]
	_ = x[YellowCrate-12]
}

const _NodeState_name = "EmptyConeCubeTwoConesTwoCubesConeThenCubeCubeThenConeNodeStateCountBlueCargoGearRedCargoWhiteCrateYellowCrate"

var _NodeState_index = [...]uint8{0, 5, 9, 13, 21, 29, 41, 53, 67, 76, 80, 88, 98, 109}

func (i NodeState) String() string {
	if i < 0 || i >= NodeState(len(_NodeState_index)-1) {
		return "NodeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeState_name[_NodeState_index[i]:_NodeState_index[i+1]]
}
