#!/bin/sh
set -e
rm -rf db/backups
rm -rf static/logs
mkdir -p static/logs
go clean
go build
zip -r -X cheesy-arena.zip LICENSE README.md ap_config.txt cheesy-arena cheesy-arena.command db font schedules static switch_config.txt templates
