// Code generated by "stringer -type=coil"; DO NOT EDIT.

package field

import "strconv"

const _coil_name = "heartbeatstackLightGreenstackLightOrangestackLightRedstackLightBluecoilCount"

var _coil_index = [...]uint8{0, 9, 24, 40, 53, 67, 76}

func (i coil) String() string {
	if i < 0 || i >= coil(len(_coil_index)-1) {
		return "coil(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _coil_name[_coil_index[i]:_coil_index[i+1]]
}
