// Code generated by "stringer -type=input"; DO NOT EDIT.

package field

import "strconv"

const _input_name = "fieldEstopredEstop1redEstop2redEstop3blueEstop1blueEstop2blueEstop3redConnected1redConnected2redConnected3blueConnected1blueConnected2blueConnected3scaleNearscaleFarredSwitchNearredSwitchFarblueSwitchNearblueSwitchFarredForceActivateredLevitateActivateredBoostActivateblueForceActivateblueLevitateActivateblueBoostActivateinputCount"

var _input_index = [...]uint16{0, 10, 19, 28, 37, 47, 57, 67, 80, 93, 106, 120, 134, 148, 157, 165, 178, 190, 204, 217, 233, 252, 268, 285, 305, 322, 332}

func (i input) String() string {
	if i < 0 || i >= input(len(_input_index)-1) {
		return "input(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _input_name[_input_index[i]:_input_index[i+1]]
}
