// Code generated by "stringer -type=armorBlock"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[redDs-0]
	_ = x[blueDs-1]
	_ = x[hub-2]
	_ = x[armorBlockCount-3]
}

const _armorBlock_name = "redDsblueDshubarmorBlockCount"

var _armorBlock_index = [...]uint8{0, 5, 11, 14, 29}

func (i armorBlock) String() string {
	if i < 0 || i >= armorBlock(len(_armorBlock_index)-1) {
		return "armorBlock(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _armorBlock_name[_armorBlock_index[i]:_armorBlock_index[i+1]]
}
