// Code generated by "stringer -type coil"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[heartbeat-0]
	_ = x[matchReset-1]
	_ = x[stackLightGreen-2]
	_ = x[stackLightOrange-3]
	_ = x[stackLightRed-4]
	_ = x[stackLightBlue-5]
	_ = x[stackLightBuzzer-6]
	_ = x[fieldResetLight-7]
	_ = x[powerPortMotors-8]
	_ = x[redStage1Light-9]
	_ = x[redStage2Light-10]
	_ = x[redStage3Light-11]
	_ = x[blueStage1Light-12]
	_ = x[blueStage2Light-13]
	_ = x[blueStage3Light-14]
	_ = x[redTrussLight-15]
	_ = x[blueTrussLight-16]
	_ = x[redControlPanelLight-17]
	_ = x[blueControlPanelLight-18]
	_ = x[coilCount-19]
}

const _coil_name = "heartbeatmatchResetstackLightGreenstackLightOrangestackLightRedstackLightBluestackLightBuzzerfieldResetLightpowerPortMotorsredStage1LightredStage2LightredStage3LightblueStage1LightblueStage2LightblueStage3LightredTrussLightblueTrussLightredControlPanelLightblueControlPanelLightcoilCount"

var _coil_index = [...]uint16{0, 9, 19, 34, 50, 63, 77, 93, 108, 123, 137, 151, 165, 180, 195, 210, 223, 237, 257, 278, 287}

func (i coil) String() string {
	if i < 0 || i >= coil(len(_coil_index)-1) {
		return "coil(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _coil_name[_coil_index[i]:_coil_index[i+1]]
}
