// Code generated by "stringer -type=input"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldEStop-0]
	_ = x[red1EStop-16]
	_ = x[red1AStop-17]
	_ = x[red2EStop-18]
	_ = x[red2AStop-19]
	_ = x[red3EStop-20]
	_ = x[red3AStop-21]
	_ = x[redConnected1-22]
	_ = x[redConnected2-23]
	_ = x[redConnected3-24]
	_ = x[blue1EStop-32]
	_ = x[blue1AStop-33]
	_ = x[blue2EStop-34]
	_ = x[blue2AStop-35]
	_ = x[blue3EStop-36]
	_ = x[blue3AStop-37]
	_ = x[blueConnected1-38]
	_ = x[blueConnected2-39]
	_ = x[blueConnected3-40]
	_ = x[inputCount-41]
}

const (
	_input_name_0 = "fieldEStop"
	_input_name_1 = "red1EStopred1AStopred2EStopred2AStopred3EStopred3AStopredConnected1redConnected2redConnected3"
	_input_name_2 = "blue1EStopblue1AStopblue2EStopblue2AStopblue3EStopblue3AStopblueConnected1blueConnected2blueConnected3inputCount"
)

var (
	_input_index_1 = [...]uint8{0, 9, 18, 27, 36, 45, 54, 67, 80, 93}
	_input_index_2 = [...]uint8{0, 10, 20, 30, 40, 50, 60, 74, 88, 102, 112}
)

func (i input) String() string {
	switch {
	case i == 0:
		return _input_name_0
	case 16 <= i && i <= 24:
		i -= 16
		return _input_name_1[_input_index_1[i]:_input_index_1[i+1]]
	case 32 <= i && i <= 41:
		i -= 32
		return _input_name_2[_input_index_2[i]:_input_index_2[i+1]]
	default:
		return "input(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
