// Code generated by "stringer -type=input"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldEStop-0]
	_ = x[red1EStop-1]
	_ = x[red1AStop-2]
	_ = x[red2EStop-3]
	_ = x[red2AStop-4]
	_ = x[red3EStop-5]
	_ = x[red3AStop-6]
	_ = x[blue1EStop-7]
	_ = x[blue1AStop-8]
	_ = x[blue2EStop-9]
	_ = x[blue2AStop-10]
	_ = x[blue3EStop-11]
	_ = x[blue3AStop-12]
	_ = x[redConnected1-13]
	_ = x[redConnected2-14]
	_ = x[redConnected3-15]
	_ = x[blueConnected1-16]
	_ = x[blueConnected2-17]
	_ = x[blueConnected3-18]
	_ = x[redHubSensor1-19]
	_ = x[redHubSensor2-20]
	_ = x[redHubSensor3-21]
	_ = x[redHubSensor4-22]
	_ = x[blueHubSensor1-23]
	_ = x[blueHubSensor2-24]
	_ = x[blueHubSensor3-25]
	_ = x[blueHubSensor4-26]
	_ = x[inputCount-27]
}

const _input_name = "fieldEStopred1EStopred1AStopred2EStopred2AStopred3EStopred3AStopblue1EStopblue1AStopblue2EStopblue2AStopblue3EStopblue3AStopredConnected1redConnected2redConnected3blueConnected1blueConnected2blueConnected3redHubSensor1redHubSensor2redHubSensor3redHubSensor4blueHubSensor1blueHubSensor2blueHubSensor3blueHubSensor4inputCount"

var _input_index = [...]uint16{0, 10, 19, 28, 37, 46, 55, 64, 74, 84, 94, 104, 114, 124, 137, 150, 163, 177, 191, 205, 218, 231, 244, 257, 271, 285, 299, 313, 323}

func (i input) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_input_index)-1 {
		return "input(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _input_name[_input_index[idx]:_input_index[idx+1]]
}
