// Code generated by "stringer -type=register"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[registerCount-0]
}

const _register_name = "registerCount"

var _register_index = [...]uint8{0, 13}

func (i register) String() string {
	if i < 0 || i >= register(len(_register_index)-1) {
		return "register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _register_name[_register_index[i]:_register_index[i+1]]
}
